import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';

// Load environment variables
dotenv.config({ path: path.join(__dirname, '../.env') });

import User from '../src/models/User';
import Complaint from '../src/models/Complaint';

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/ruraltrust';

const VILLAGES = ['Tambaram', 'Velachery', 'Chitlapakkam', 'Kovalam', 'Thiruporur', 'Siruseri'];
const PROBLEM_TYPES = ['Water Supply', 'Sanitation', 'Road Damage', 'Electricity', 'Healthcare', 'Street Lights', 'Waste Management'];
const PRIORITIES = ['High', 'Medium', 'Low'];

// Helper to get random item from array
const getRandom = <T>(arr: T[]): T => arr[Math.floor(Math.random() * arr.length)];

// Helper to get random number between min and max
const getRandomInt = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min;

const generateComplaintsForCitizen = (citizenId: mongoose.Types.ObjectId, count: number) => {
    const complaints = [];

    for (let i = 0; i < count; i++) {
        const problemType = getRandom(PROBLEM_TYPES);
        const priority = getRandom(PRIORITIES);

        let urgency = 5;
        if (priority === 'High') urgency = getRandomInt(8, 10);
        else if (priority === 'Medium') urgency = getRandomInt(4, 7);
        else urgency = getRandomInt(1, 3);

        complaints.push({
            citizenId,
            village: getRandom(VILLAGES),
            problemType,
            problemTypes: [{ category: problemType, confidence: 0.95 }],
            description: `Automated test complaint regarding ${problemType} in the area. Please looking into it.`,
            language: 'en',
            translatedDescription: `Automated test complaint regarding ${problemType} in the area. Please looking into it.`,
            priority,
            priorityScore: Math.random(),
            urgency,
            eta: `${getRandomInt(1, 5)} days`,
            etaMinDays: 1,
            etaMaxDays: 5,
            reasoning: 'Generated by bulk seeding script for load testing.',
            status: 'active',
            isPrimary: true
        });
    }

    return complaints;
};

async function runSeeder() {
    try {
        console.log('Connecting to MongoDB...');
        await mongoose.connect(MONGO_URI);
        console.log('✅ Connected to MongoDB');

        // Find all citizens
        let citizens = await User.find({ type: 'citizen' });
        console.log(`Found ${citizens.length} citizens in the database.`);

        if (citizens.length === 0) {
            console.log('⚠️ No citizens found. Automatically creating 10 dummy citizen accounts...');
            const dummyCitizens = [];
            for (let i = 0; i < 10; i++) {
                dummyCitizens.push({
                    type: 'citizen',
                    name: `Citizen ${i + 1}`,
                    mobile: `+91987654321${i}`,
                    village: getRandom(VILLAGES),
                    status: 'active'
                });
            }
            await User.insertMany(dummyCitizens);
            citizens = await User.find({ type: 'citizen' });
            console.log(`✅ Successfully created ${citizens.length} dummy citizens.`);
        }

        let totalComplaintsInserted = 0;

        console.log('Generating complaints...');
        for (const citizen of citizens) {
            // Give each citizen 5 to 15 complaints
            const count = getRandomInt(5, 15);
            const complaintsToInsert = generateComplaintsForCitizen(citizen._id, count);

            await Complaint.insertMany(complaintsToInsert);
            totalComplaintsInserted += count;
            console.log(`Inserted ${count} complaints for citizen ${citizen.mobile || citizen._id}`);
        }

        console.log(`\n✅ Success! Total of ${totalComplaintsInserted} complaints were successfully inserted across ${citizens.length} citizens.`);

    } catch (error) {
        console.error('❌ Error during database seeding:', error);
    } finally {
        await mongoose.disconnect();
        console.log('Disconnected from MongoDB.');
        process.exit(0);
    }
}

runSeeder();
